appender.0.type = Console
appender.0.name = CONSOLE
appender.0.layout.type = PatternLayout
appender.0.layout.pattern = [%-5p] %d{yyyy-mm-dd\u2019T\u2019HH:mm:ss.SSS\u2019Z'}{UTC} [%t]: %m%n

rootLogger.level = DEBUG
rootLogger.additivity = true
rootLogger.appenderRef.0.ref = CONSOLE

logger.0.name = org.springframework
logger.0.level = DEBUG
logger.0.additivity = false
logger.0.appenderRef.0.ref = CONSOLE

logger.1.name = com.thorben
logger.1.level = DEBUG
logger.1.additivity = false
logger.1.appenderRef.0.ref = CONSOLE